# ===============
# Project Context
# ===============
project:
  domain: "Medical Imaging & Diagnostics"
  context_statement: "diagnosing skin lesions as benign or malignant from dermatoscopic images"
  use_case: "educational_curriculum"

# ================
# Dataset Settings
# ================
dataset:
  root_path: "/fs/ess/PAS2699/digitalAgEdu_datasets/skin_cancer_dataset"
  structure: "folder_per_class" # Looking through each folder within the path as a class

  # ML Settings
  train_split: 0.8
  validation_split: 0.2
  ignore_list: [.DS_Store]
  save_class_mapping: true # Generates the .json mapping 

output:
  directory: "./outputs/skin_cancer_v1"
  save_plots: true
  artifact_path: "./models/artifacts"

# ================
# Pipeline Stages
# ================
pipeline:
  stages:
    - name: "Classification"
      active: true
      task_type: "medical_classification"
      module: "curriculum_resources.week_08.solution" # Where the logic is
      model_path: "models/dinov2_skin_cancer_v2.pth"

    - name: "Segmentation"
      active: true
      task_type: "object_extraction"
      module: "curriculum_resources.week_09.solution"
      model_path: "models/sam_vit_b.pth"
      prompt: "the skin lesion or mole, the dark spot on the skin" # Prompt for SAM

    - name: "VisionQA"
      active: true
      task_type: "visual_question_answering"
      module: "curriculum_resources.week_11.solution"
      prompt:  "Based on the classification provided, analyze the visual characteristics of the image that support this conclusion. Provide a concise 2-sentence explanation of the visual evidence."
      target_metric: "diagnosis_reasoning"

# ============
# Execution
#=============
execution:
  environment: "local" # local for now, OSC when running on cluster
  device: "cuda" # cpu or cuda
  batch_size: 16
  image_size: 518
  max_samples: null
  seed: 6767


# ==================
# Curriculum Config
# ==================
curriculum:
  subject: "Intro to Medical AI: Skin Cancer Diagnostics"
  grade: 10
  weeks: 24

  topics:
    - name: "Skin Lesion Classification"
      description: "Learn to build a vision model that can classify skin lesions as benign or malignant."
      project: "Skin Cancer Diagnostic AI"

  resources:
    - name: "Skin Cancer Dataset Source"
      url: "https://www.kaggle.com/datasets/fanconic/skin-cancer-malignant-vs-benign"
    - name: "DINOv2 Documentation"
      url: "https://huggingface.co/docs/transformers/en/model_doc/dinov2"
