# ===============
# Project Context
# ===============
project:
  domain: "Computer Vision & Game Theory"
  context_statement: "recognizing human hand gestures to automate Rock, Paper, Scissors"
  use_case: "educational_curriculum"

# ================
# Dataset Settings
# ================
dataset:
  root_path: "C:/Desktop/Coding Projects/curriculum_generator/test_datasets"
  structure: "folder_per_class" # Looking through each folder within the path as a class

  # ML Settings
  train_split: 0.8
  validation_split: 0.2
  ignore_list: [.DS_Store]
  save_class_mapping: true # Generates the .json mapping 

output:
  directory: "./outputs/rock_paper_scissors_v1"
  save_plots: true
  artifact_path: "./models/artifacts"

# ================
# Pipeline Stages
# ================
pipeline:
  stages:
    - name: "Classification"
      active: true
      task_type: "gesture_recognition"
      module: "curriculum_resources.week_08.solution" # Where the logic is
      model_path: "models/dinov2_vitb14_rps_best.pt"

    - name: "Segmentation"
      active: true
      task_type: "object_extraction"
      module: "curriculum_resources.week_09.solution"
      prompt: "the human hand" # Prompt for SAM

    - name: "Analysis"
      active: false
      task_type: "percentage_estimation"
      module: "curriculum_resources.week_10.solution"
      target_metric: "hand_area_ratio"

# ============
# Execution
#=============
execution:
  environment: "local" # local for now, OSC when running on cluster
  device: "cpu" # cpu or cuda
  batch_size: 32
  image_size: 518
  max_samples: 5


# ==================
# Curriculum Config
# ==================
curriculum:
  subject: "Intro to Computer Vision: Rock Paper Scissors"
  grade: 10
  weeks: 12

  topics:
    - name: "Hand Gesture Recognition"
      description: "Learn to build a vision model that can classify rock, paper, and scissors hand signs."
      project: "Rock Paper Scissors Bot"

  resources:
    - name: "Rock Paper Scissors Dataset Source"
      url: "https://www.kaggle.com/datasets/sanikamal/rock-paper-scissors-dataset"
    - name: "DINOv2 Documentation"
      url: "https://huggingface.co/docs/transformers/en/model_doc/dinov2"