# ===============
# Project Context
# ===============
project:
  domain: "Plant Pathology" # ex: Radiology, Geology, the domain
  context_statement: "detecting bacterial damage to optimize crop yield"
  use_case: "educational_curriculum"

# ================
# Dataset Settings
# ================
dataset:
  root_path: "C:/Desktop/Coding Projects/curriculum_generator/test_datasets"
  structure: "folder_per_class" # Looking through each folder within the path as a class

  # ML Settings
  train_split: 0.8
  validation_split: 0.2
  ignore_list: [.DS_Store]
  save_class_mapping: true # Generates the .json mapping 

output:
  directory: "./outputs/bell_pepper_v1"
  save_plots: true
  artifact_path: "./models/artifacts"

# ================
# Pipeline Stages
# ================
pipeline:
  stages:
    - name: "Classification"
      active: true
      task_type: "disease_detection"
      module: "curriculum_resources.week_08.solution" # Where the logic is
      model_path: "models/dinov2_vitb14_best.pt"

    - name: "Segmentation"
      active: true
      task_type: "object_extraction"
      module: "curriculum_resources.week_09.solution"
      prompt: "the diseased area of the leaf" # Prompt for SAM

    - name: "Analysis"
      active: true
      task_type: "percentage_estimation"
      module: "curriculum_resources.week_10.solution"
      target_metric: "damage_ratio"

# ============
# Execution
#=============
execution:
  environment: "local" # local for now, OSC when running on cluster
  device: "cpu" # cpu or cuda
  batch_size: 32
  image_size: 518


# ==================
# Curriculum Config
# ==================
curriculum:
  subject: "Bell Pepper Bacterial Classification"
  grade: 10
  weeks: 12

  topics:
    - name: "Deep Learning for Plant Pathology"
      description: "Learn to identify bacterial sports on bell peppers using DINOv2"
      project: "Bell Pepper DIsease Classifier"

    - name: "Deep Learning for Plant Pathology 2"
      description: "This is to test the second block"
      project: "Black Pepper Classifier"

  resources:
    - name: "DINOv2 Documentation"
      url: "https://huggingface.co/docs/transformers/en/model_doc/dinov2"