import type { CurriculumModule, CurriculumResource } from '../presets';

export interface ConfigFormData {
  domain: string;
  contextStatement: string;
  useCase?: string;
  datasetPath: string;
  outputPath: string;
  classificationActive: boolean;
  classificationTask: string;
  segmentationActive: boolean;
  segmentationPrompt: string;
  xaiActive: boolean;
  device: string;
  batchSize: number;
  imageSize: number;
  seed: number;
  llmModel: string;
  subject: string;
  targetLevel: string;
  modules: CurriculumModule[];
  topicName?: string;
  topicDescription?: string;
  resources?: CurriculumResource[];
}

/**
 * Pure utility function to convert form state into verified YAML format for the pipeline.
 */
export function generateCurriculumYaml(data: ConfigFormData): string {
  const {
    domain,
    contextStatement,
    useCase = 'educational_curriculum',
    datasetPath,
    outputPath,
    classificationActive,
    classificationTask,
    segmentationActive,
    segmentationPrompt,
    xaiActive,
    device,
    batchSize,
    imageSize,
    seed,
    llmModel,
    subject,
    targetLevel,
    modules,
    topicName,
    topicDescription,
    resources = [],
  } = data;

  let yaml = `# ==============================================================================
# SMART CURRICULUM DESIGNER CONFIGURATION
# Auto-generated by Smart Curriculum Designer Builder
# ==============================================================================

# ===============
# Project Context
# ===============
project:
  domain: "${domain}"
  context_statement: "${contextStatement}"
  use_case: "${useCase}"

# ================
# Dataset Settings
# ================
dataset:
  root_path: "${datasetPath}"

# ================
# Output Directory
# ================
output:
  directory: "${outputPath}"

# ================
# Pipeline Stages
# ================
pipeline:
`;

  const hasStages = classificationActive || segmentationActive || xaiActive;
  if (!hasStages) {
    yaml += `  stages: []\n`;
  } else {
    yaml += `  stages:\n`;
    if (classificationActive) {
      yaml += `    - name: "Classification"
      active: true
      task_type: "${classificationTask}"
`;
    }
    if (segmentationActive) {
      yaml += `    - name: "Segmentation"
      active: true
      task_type: "object_extraction"
      prompt: "${segmentationPrompt}"
`;
    }
    if (xaiActive) {
      yaml += `    - name: "VisualXAI"
      active: true
      task_type: "visual_explainibility"
`;
    }
  }

  yaml += `
# ============
# Execution
# ============
execution:
  device: "${device}"
  batch_size: ${batchSize}
  image_size: ${imageSize}
  seed: ${seed}
  use_llm: true
  llm_model: "${llmModel}"

# ==================
# Curriculum Config
# ==================
curriculum:
  subject: "${subject}"
  target_level: "${targetLevel}"
  model: "${llmModel}"

`;

  if (modules.length === 0) {
    yaml += `  modules: []\n`;
  } else {
    yaml += `  modules:\n`;
    modules.forEach((m) => {
      yaml += `    - id: "${m.id}"
      title: "${m.title}"
      week: ${m.week}
      difficulty: "${m.difficulty.toLowerCase()}"
      context: "${m.context}"
`;
      if (m.learning_outcomes && m.learning_outcomes.length > 0) {
        yaml += `      learning_outcomes:\n`;
        m.learning_outcomes.forEach((lo) => {
          yaml += `        - "${lo.replace(/"/g, '\\"')}"\n`;
        });
      }
    });
  }

  if (topicName || topicDescription) {
    yaml += `
  topics:
    - name: "${topicName || subject}"
      description: "${topicDescription || ''}"
      project: "${topicName || subject}"
`;
  }

  if (resources.length === 0) {
    yaml += `\n  resources: []\n`;
  } else {
    yaml += `\n  resources:\n`;
    resources.forEach((r) => {
      yaml += `    - name: "${r.name}"
      url: "${r.url}"
`;
    });
  }

  return yaml;
}
