name: Build and Push Docker Image

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# Run script on push or through GitHub Actions run button
on:
  push:
    branches:
      - main
      - feature/sprint_one
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Logs into Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Builds the Dockerfile and pushes it to Docker Hub
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jassehxia/digital-age-edu:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
